######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 9 14:02:11 2010
######################################################################

TEMPLATE = app
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR = objects_moc 
MOC_DIR = objects_moc

# Input
HEADERS += ../../src/data/data.h \
           ../../src/data/book_author.h \
           ../../src/data/xml_parser/parser.h \
           ../../src/data/xml_parser/handler.h \
           ../../src/data/xml_writer/data_writer.h
SOURCES += main.cpp \
           ../../src/data/data.cpp \
           ../../src/data/book_author.cpp \
           ../../src/data/xml_parser/parser.cpp \
           ../../src/data/xml_parser/handler.cpp \
           ../../src/data/xml_writer/data_writer.cpp
