######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 5 16:08:55 2010
######################################################################

TEMPLATE = app
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
MOC_DIR = bin
OBJECTS_DIR = bin

# Input
HEADERS += ../../src/data/data.h \
           ../../src/data/book_author.h \
           ../../src/data/opds_parser/parser.h \
           ../../src/data/opds_parser/handler.h \
           ../../src/data/search_result.h \
           ../../src/data/opds_parser/opds_constants.h \
           ../../src/data/opds_parser/XMLInputSource.h \
           ../../src/data/opds_writer/opds_writer.h
SOURCES += main.cpp \
           ../../src/data/data.cpp \
           ../../src/data/book_author.cpp \
           ../../src/data/opds_parser/parser.cpp \
           ../../src/data/opds_parser/handler.cpp \
           ../../src/data/search_result.cpp \
           ../../src/data/opds_parser/opds_constants.cpp \
           ../../src/data/opds_parser/XMLInputSource.cpp \
           ../../src/data/opds_writer/opds_writer.cpp
