######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 22 17:37:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += settings.cpp
