######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 17 18:29:30 2010
######################################################################

TEMPLATE = app
QT += network
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
MOC_DIR = bin
OBJECTS_DIR = bin

# Input
HEADERS += src/loader.h ../../../src/network/networkmanager.h
SOURCES += src/loader.cpp src/main.cpp ../../../src/network/networkmanager.cpp
