#!/bin/bash

CONF_FILE='sphinx.conf'

echo "# It file was generated by sphinx_conf_gen.sh" > $CONF_FILE
echo "# Please, do NOT change it" >> $CONF_FILE
echo "# If you want to change conf file, change .tmplt files" >> $CONF_FILE

for template in *.tmplt; do
    echo >> $CONF_FILE
    echo "#" >> $CONF_FILE
    echo "# Content from file $template" >> $CONF_FILE
    echo "#" >> $CONF_FILE

    cat $template >> $CONF_FILE
done
