######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 7 16:40:11 2010
######################################################################

TEMPLATE = app
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test.h \
           tester.h \
           ../src/data/data.h \
           ../src/data/book_author.h \
           ../src/data/xml_parser/parser.h \
           ../src/data/xml_parser/handler.h \
           ../src/data/xml_writer/data_writer.h
SOURCES += main.cpp \
           test.cpp \
           tester.cpp \
           ../src/data/data.cpp \
           ../src/data/book_author.cpp \
           ../src/data/xml_parser/parser.cpp \
           ../src/data/xml_parser/handler.cpp \
           ../src/data/xml_writer/data_writer.cpp
